name: gymf
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3 # آخرین نسخه که گفتi
  provider: ^6.1.1
  http: ^1.2.0
  flutter_spinkit: ^5.2.0
  animations: ^2.0.7
  google_fonts: ^6.1.0
  crypto: ^3.0.3
  google_sign_in: ^6.2.2
  uuid: ^4.5.1
  google_nav_bar: ^5.0.7
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  animate_do: ^4.2.0
  shared_preferences: ^2.5.2
  flutter_animate: ^4.5.2
  flutter_typeahead: ^5.2.0
  debounce_throttle: ^2.0.0
  


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0




flutter:

 
  uses-material-design: true

  assets:
    - images/
